"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.yellow_under = exports.yellow_strike = exports.yellow_light = exports.yellow_italic = exports.yellow_invert = exports.yellow_bold = exports.yellow = exports.white_under = exports.white_strike = exports.white_light = exports.white_italic = exports.white_invert = exports.white_bold = exports.white = exports.uncolor = exports.red_under = exports.red_strike = exports.red_light = exports.red_italic = exports.red_invert = exports.red_bold = exports.red = exports.magenta_under = exports.magenta_strike = exports.magenta_light = exports.magenta_italic = exports.magenta_invert = exports.magenta_bold = exports.magenta = exports.green_under = exports.green_strike = exports.green_light = exports.green_italic = exports.green_invert = exports.green_bold = exports.green = exports.gray_under = exports.gray_strike = exports.gray_light = exports.gray_italic = exports.gray_invert = exports.gray_bold = exports.gray = exports.cyan_under = exports.cyan_strike = exports.cyan_light = exports.cyan_italic = exports.cyan_invert = exports.cyan_bold = exports.cyan = exports.blue_under = exports.blue_strike = exports.blue_light = exports.blue_italic = exports.blue_invert = exports.blue_bold = exports.blue = exports.black_under = exports.black_strike = exports.black_light = exports.black_italic = exports.black_invert = exports.black_bold = exports.black = void 0;
var _code = (mod, num_code) => "\x1B[".concat(mod).concat(num_code, "m");
var _reset = "\x1B[0;39m";
var black = s => _code('0;', '30') + s + _reset;
exports.black = black;
var black_bold = s => _code('1;', '30') + s + _reset;
exports.black_bold = black_bold;
var black_light = s => _code('2;', '30') + s + _reset;
exports.black_light = black_light;
var black_italic = s => _code('3;', '30') + s + _reset;
exports.black_italic = black_italic;
var black_under = s => _code('4;', '30') + s + _reset;
exports.black_under = black_under;
var black_invert = s => _code('7;', '30') + s + _reset;
exports.black_invert = black_invert;
var black_strike = s => _code('9;', '30') + s + _reset;
exports.black_strike = black_strike;
var red = s => _code('0;', '31') + s + _reset;
exports.red = red;
var red_bold = s => _code('1;', '31') + s + _reset;
exports.red_bold = red_bold;
var red_light = s => _code('2;', '31') + s + _reset;
exports.red_light = red_light;
var red_italic = s => _code('3;', '31') + s + _reset;
exports.red_italic = red_italic;
var red_under = s => _code('4;', '31') + s + _reset;
exports.red_under = red_under;
var red_invert = s => _code('7;', '31') + s + _reset;
exports.red_invert = red_invert;
var red_strike = s => _code('9;', '31') + s + _reset;
exports.red_strike = red_strike;
var green = s => _code('0;', '32') + s + _reset;
exports.green = green;
var green_bold = s => _code('1;', '32') + s + _reset;
exports.green_bold = green_bold;
var green_light = s => _code('2;', '32') + s + _reset;
exports.green_light = green_light;
var green_italic = s => _code('3;', '32') + s + _reset;
exports.green_italic = green_italic;
var green_under = s => _code('4;', '32') + s + _reset;
exports.green_under = green_under;
var green_invert = s => _code('7;', '32') + s + _reset;
exports.green_invert = green_invert;
var green_strike = s => _code('9;', '32') + s + _reset;
exports.green_strike = green_strike;
var yellow = s => _code('0;', '33') + s + _reset;
exports.yellow = yellow;
var yellow_bold = s => _code('1;', '33') + s + _reset;
exports.yellow_bold = yellow_bold;
var yellow_light = s => _code('2;', '33') + s + _reset;
exports.yellow_light = yellow_light;
var yellow_italic = s => _code('3;', '33') + s + _reset;
exports.yellow_italic = yellow_italic;
var yellow_under = s => _code('4;', '33') + s + _reset;
exports.yellow_under = yellow_under;
var yellow_invert = s => _code('7;', '33') + s + _reset;
exports.yellow_invert = yellow_invert;
var yellow_strike = s => _code('9;', '33') + s + _reset;
exports.yellow_strike = yellow_strike;
var blue = s => _code('0;', '34') + s + _reset;
exports.blue = blue;
var blue_bold = s => _code('1;', '34') + s + _reset;
exports.blue_bold = blue_bold;
var blue_light = s => _code('2;', '34') + s + _reset;
exports.blue_light = blue_light;
var blue_italic = s => _code('3;', '34') + s + _reset;
exports.blue_italic = blue_italic;
var blue_under = s => _code('4;', '34') + s + _reset;
exports.blue_under = blue_under;
var blue_invert = s => _code('7;', '34') + s + _reset;
exports.blue_invert = blue_invert;
var blue_strike = s => _code('9;', '34') + s + _reset;
exports.blue_strike = blue_strike;
var magenta = s => _code('0;', '35') + s + _reset;
exports.magenta = magenta;
var magenta_bold = s => _code('1;', '35') + s + _reset;
exports.magenta_bold = magenta_bold;
var magenta_light = s => _code('2;', '35') + s + _reset;
exports.magenta_light = magenta_light;
var magenta_italic = s => _code('3;', '35') + s + _reset;
exports.magenta_italic = magenta_italic;
var magenta_under = s => _code('4;', '35') + s + _reset;
exports.magenta_under = magenta_under;
var magenta_invert = s => _code('7;', '35') + s + _reset;
exports.magenta_invert = magenta_invert;
var magenta_strike = s => _code('9;', '35') + s + _reset;
exports.magenta_strike = magenta_strike;
var cyan = s => _code('0;', '36') + s + _reset;
exports.cyan = cyan;
var cyan_bold = s => _code('1;', '36') + s + _reset;
exports.cyan_bold = cyan_bold;
var cyan_light = s => _code('2;', '36') + s + _reset;
exports.cyan_light = cyan_light;
var cyan_italic = s => _code('3;', '36') + s + _reset;
exports.cyan_italic = cyan_italic;
var cyan_under = s => _code('4;', '36') + s + _reset;
exports.cyan_under = cyan_under;
var cyan_invert = s => _code('7;', '36') + s + _reset;
exports.cyan_invert = cyan_invert;
var cyan_strike = s => _code('9;', '36') + s + _reset;
exports.cyan_strike = cyan_strike;
var white = s => _code('0;', '37') + s + _reset;
exports.white = white;
var white_bold = s => _code('1;', '37') + s + _reset;
exports.white_bold = white_bold;
var white_light = s => _code('2;', '37') + s + _reset;
exports.white_light = white_light;
var white_italic = s => _code('3;', '37') + s + _reset;
exports.white_italic = white_italic;
var white_under = s => _code('4;', '37') + s + _reset;
exports.white_under = white_under;
var white_invert = s => _code('7;', '37') + s + _reset;
exports.white_invert = white_invert;
var white_strike = s => _code('9;', '37') + s + _reset;
exports.white_strike = white_strike;
var gray = s => _code('0;', '38') + s + _reset;
exports.gray = gray;
var gray_bold = s => _code('1;', '38') + s + _reset;
exports.gray_bold = gray_bold;
var gray_light = s => _code('2;', '38') + s + _reset;
exports.gray_light = gray_light;
var gray_italic = s => _code('3;', '38') + s + _reset;
exports.gray_italic = gray_italic;
var gray_under = s => _code('4;', '38') + s + _reset;
exports.gray_under = gray_under;
var gray_invert = s => _code('7;', '38') + s + _reset;
exports.gray_invert = gray_invert;
var gray_strike = s => _code('9;', '38') + s + _reset;
exports.gray_strike = gray_strike;
var uncolor = s =>
// eslint-disable-next-line no-control-regex
s.replace(/[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g, '');
exports.uncolor = uncolor;
